### ISSUE TITLE
[ZEON] - recommended additions

### ISSUE THREAD

**Issue by zeon-neon** [NeonGamerBot-QK/catppuccin-libre-office#4]
# Meta

- [ ] Github repo has no description

- [ ] There is no homepage!

- [ ] Your default branch is not 'main' please update it.

- [ ] Your repo does not have web commit signing off enabled. **PLEASE ENABLE IT**
# Automation

- [ ] **Mark this to override & close this issue.**
